### ISSUE TITLE
Andere kleurenpalette 

### ISSUE THREAD

**Issue by Tolga1999** [kosterm14/connect-your-tribe-profile-card#1]
Neem een andere kleurenpalette, zwart met zachte kleuren als background werkt niet echt

**Comment by kosterm14** [comment]
![image](https://user-images.githubusercontent.com/61830362/230495159-8f7ffca1-737c-46fb-ad91-7e64d3bfabe3.png)

Dank je ik heb het kleurenpalette aangepast:)
