### ISSUE TITLE
Week 1 sprint 7 - gesprek reflectie

### ISSUE THREAD

**Issue by Tolga1999** [kosterm14/connect-your-tribe-profile-card#6]
Het gesprek met Marco ging heel goed en soepel. Marco heeft mij een paar issues geschreven en uitgelegd wat ze betekenen. Marco was serieus en erg behulpzaam tijdens het gesprek. Samenwerken met Marco ging heel goed.

**Comment by kosterm14** [comment]
dank je voor je feedback!
